version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2024.01
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Google Cloud SDK
          command: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get install google-cloud-cli -y
      - run:
          name: Authenticate with google cloud
          command: |
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
              gcloud auth activate-service-account --key-file=gcp-key.json
              gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Build and Push Image
          command: |
              docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/iot-support-repo/iot-support-chatbot:latest .
              docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/iot-support-repo/iot-support-chatbot:latest

  deploy_to_gke:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Google Cloud SDK and kubectl
          command: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get install google-cloud-cli kubectl google-cloud-cli-gke-gcloud-auth-plugin -y
            echo 'export USE_GKE_GCLOUD_AUTH_PLUGIN=True' >> $BASH_ENV
      - run:
          name: Authenticate with google cloud
          command: |
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
              gcloud auth activate-service-account --key-file=gcp-key.json
              gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker
      
      - run:
          name: Configure GKE
          command: |
              gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
      
      - run:
          name: Substitute environment variables
          command: |
              echo "Available environment variables:"
              env | grep -E "(GROQ|MYSQL|DEBUG|FEEDBACK)" || echo "No matching environment variables found"
              echo "Running envsubst..."
              envsubst < kubernetes-deployment.yaml > kubernetes-deployment-substituted.yaml
              echo "Substituted file contents:"
              cat kubernetes-deployment-substituted.yaml
      
      - run:
          name: Deploy to GKE
          command: |
              kubectl apply -f kubernetes-deployment-substituted.yaml --validate=false
              kubectl rollout restart deployment iot-support-chatbot

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image 